const stylesheet = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:i="http://www.google.com/schemas/sitemap-image/1.1">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template name="display-date">
    <xsl:param name="value"/>
    <xsl:choose>
      <xsl:when test="substring($value, 6, 2) = '01'">January</xsl:when><xsl:when test="substring($value, 6, 2) = '02'">February</xsl:when><xsl:when test="substring($value, 6, 2) = '03'">March</xsl:when><xsl:when test="substring($value, 6, 2) = '04'">April</xsl:when><xsl:when test="substring($value, 6, 2) = '05'">May</xsl:when><xsl:when test="substring($value, 6, 2) = '06'">June</xsl:when><xsl:when test="substring($value, 6, 2) = '07'">July</xsl:when><xsl:when test="substring($value, 6, 2) = '08'">August</xsl:when><xsl:when test="substring($value, 6, 2) = '09'">September</xsl:when><xsl:when test="substring($value, 6, 2) = '10'">October</xsl:when><xsl:when test="substring($value, 6, 2) = '11'">November</xsl:when><xsl:otherwise>December</xsl:otherwise>
    </xsl:choose>
    <xsl:text> </xsl:text><xsl:value-of select="number(substring($value, 9, 2))"/><xsl:text>, </xsl:text><xsl:value-of select="substring($value, 1, 4)"/><xsl:text> at </xsl:text>
    <xsl:variable name="hour" select="number(substring($value, 12, 2))"/>
    <xsl:choose><xsl:when test="$hour = 0">12</xsl:when><xsl:when test="$hour &gt; 12"><xsl:value-of select="$hour - 12"/></xsl:when><xsl:otherwise><xsl:value-of select="$hour"/></xsl:otherwise></xsl:choose>
    <xsl:text>:</xsl:text><xsl:value-of select="substring($value, 15, 2)"/><xsl:text> </xsl:text><xsl:choose><xsl:when test="$hour &gt;= 12">pm</xsl:when><xsl:otherwise>am</xsl:otherwise></xsl:choose>
  </xsl:template>
  <xsl:template match="/">
    <html>
      <head>
        <title>Sitemap | 360Airo</title>
        <style>
          * { box-sizing: border-box; }
          body { margin: 0; color: #101828; font-family: Arial, Helvetica, sans-serif; background: #fff; }
          .hero { min-height: 225px; padding: 34px; color: #fff; background: #141d3b; }
          h1 { margin: 0 0 17px; font-size: 28px; line-height: 1.2; }
          p { margin: 0 0 14px; font-size: 16px; line-height: 1.55; }
          .content { max-width: 1534px; padding: 23px 37px 48px; }
          .crumb { margin: 0 0 37px; font-size: 18px; }
          table { width: 100%; border-collapse: collapse; font-size: 14px; }
          th { padding: 8px 6px 19px; text-align: left; font-size: 16px; }
          td { height: 55px; padding: 12px 6px; border-top: 1px solid #d0d0d0; vertical-align: middle; }
          tr:nth-child(even) td { background: #f5f5f5; }
          a { color: #0000ee; }
          .hero a { color: #fff; } .count { width: 21%; } .updated { width: 27%; }
        </style>
      </head>
      <body>
        <div class="hero">
          <h1><xsl:choose><xsl:when test="s:sitemapindex">Sitemap</xsl:when><xsl:otherwise>URL Sitemap</xsl:otherwise></xsl:choose></h1>
          <p>Generated by <a href="https://aioseo.com/">All in One SEO Pro</a>, this is an XML Sitemap, meant to be consumed by search engines like Google or Bing.</p>
          <p>You can find more information about XML Sitemaps at <a style="color:#fff" href="https://www.sitemaps.org/">sitemaps.org</a>.</p>
          <xsl:choose>
            <xsl:when test="s:sitemapindex"><p>This sitemap index contains <xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps and was generated on <xsl:call-template name="display-date"><xsl:with-param name="value" select="s:sitemapindex/s:sitemap[1]/s:lastmod"/></xsl:call-template>.</p></xsl:when>
            <xsl:otherwise><p>This sitemap contains <xsl:value-of select="count(s:urlset/s:url)"/> URLs and was generated on <xsl:call-template name="display-date"><xsl:with-param name="value" select="s:urlset/s:url[1]/s:lastmod"/></xsl:call-template>.</p></xsl:otherwise>
          </xsl:choose>
        </div>
        <div class="content">
          <xsl:choose>
            <xsl:when test="s:sitemapindex">
              <p class="crumb">Home &#8250; <strong>Sitemap Index</strong></p>
              <table><thead><tr><th>URL</th><th class="count">URL Count</th><th class="updated">Last Updated</th></tr></thead><tbody>
                <xsl:for-each select="s:sitemapindex/s:sitemap">
                  <tr><td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td><td class="count"><xsl:value-of select="count(document(s:loc)/s:urlset/s:url)"/></td><td class="updated"><xsl:call-template name="display-date"><xsl:with-param name="value" select="s:lastmod"/></xsl:call-template></td></tr>
                </xsl:for-each>
              </tbody></table>
            </xsl:when>
            <xsl:otherwise>
              <p class="crumb">Home &#8250; Sitemap Index &#8250; <strong>URL Sitemap</strong></p>
              <table><thead><tr><th>URL</th><th class="count">Images</th><th class="count">Change Frequency</th><th class="count">Priority</th><th class="updated">Last Updated</th></tr></thead><tbody>
                <xsl:for-each select="s:urlset/s:url">
                  <tr><td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td><td class="count"><xsl:value-of select="count(i:image)"/></td><td class="count"><xsl:value-of select="s:changefreq"/></td><td class="count"><xsl:choose><xsl:when test="s:priority = '0.5'">Medium</xsl:when><xsl:when test="s:priority = '0.8'">High</xsl:when><xsl:otherwise>Low</xsl:otherwise></xsl:choose></td><td class="updated"><xsl:call-template name="display-date"><xsl:with-param name="value" select="s:lastmod"/></xsl:call-template></td></tr>
                </xsl:for-each>
              </tbody></table>
            </xsl:otherwise>
          </xsl:choose>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

export function GET() {
  return new Response(stylesheet, {
    headers: { 'Content-Type': 'text/xsl; charset=utf-8' },
  });
}
